language: php
dist: trusty
sudo: false
group: deprecated-2017Q4

php:
  - 7.0
  - 7.1

matrix:
  fast_finish: true

  allow_failures:
    - php: 7.0 # Does not work until https://github.com/sebastianbergmann/phpunit/issues/2754 is resolved

  include:
    - php: 7.0
      env: PHPCS=1 DEFAULT=0
    - php: 7.1
      env: PHPCS=1 DEFAULT=0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - curl -s http://getcomposer.org/installer | php
  - composer install --prefer-dist --no-interaction

before_script:
  - mkdir -p build/logs

  # show some versions and env information
  - mysql --version
  - php --version
  - composer --version

script:
  - composer require php-coveralls/php-coveralls
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover=build/logs/clover.xml; fi
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v
    - if [[ $PHPCS = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
    - if [[ $PHPCS = 1 ]]; then travis_retry php vendor/bin/coveralls -v; fi
    - php vendor/bin/codacycoverage clover build/logs/clover.xml

notifications:
  email: false

